controllers/NdtController.php
<?php // Stan 2013-09-20

namespace app\controllers;

use Yii;
use \yii\web\Controller;
use \yii\base\HttpException;

use app\models\Doc;
use app\models\Unit;
use app\models\Entry;
use app\models\Joint;
use app\models\JointEntry;

require_once 'lib/meta_array.php';
require_once 'lib/sql.php';
require_once 'lib/view.php';
require_once 'lib/common.php';


class NdtController extends Controller {
  public $layout = '@app/views/layouts/view';


  /**
  Index
   */
  public function actionIndex() {
    list($route, $params) = Yii::$app->request->resolve();

    echo $this->render('debug', array(
      'params' => $params,
    ));
  }


  /**
  Документы
   */
  public function actionDocs() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn = Doc::tableName();

    $metaArray = new \MetaArray();

    $rows = Doc::find()
              ->where( $metaArray->serialize_sql( $doc_tn ) )
              ->all();

    echo $this->render('docs', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }


  /**
  Cтыки
   */
  public function actionJoints() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn   = Doc::tableName();
    $joint_tn = Joint::tableName();
    $entry_tn = JointEntry::tableName();

    $metaArray = new \MetaArray();

    $sql = 'SELECT DISTINCT "%2$s".id, "%2$s".name
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id,
  "%2$s"
    ON "%2$s".id = _joints_id
WHERE
  %4$s AND %5$s AND %6$s
ORDER BY "%2$s".name
';
    $where4 = $metaArray->serialize_sql( $doc_tn );
    $where5 = $metaArray->serialize_sql( $joint_tn );
    $where6 = $metaArray->serialize_sql( $entry_tn );
    $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $where4, $where5, $where6 );
    $command = $connection->createCommand( $sql );
    $joints = $command->queryAll();

    $rows = array();
    foreach ( $joints as $joint ) {
      $id = $joint['id'];
      $name = $joint['name'];

      $sql = 'SELECT "%1$s".*, "%3$s".decision, "%3$s".remarks
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id
WHERE
  _joints_id = \'%4$s\'
';
      $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $id );
      $command = $connection->createCommand( $sql );
      $docs = $command->queryAll();
 
      $rows2 = array();
      foreach ( $docs as $doc ) {
        $rows2[$doc['type']][] = array($doc['name'], $doc['kind'], $doc['decision'], $doc['remarks']);
      } // foreach

      $rows[] = array($id, $name, $rows2);
    } // foreach
 
    $methods = Doc::find()
                 ->select('type')
                 ->distinct('type')
                 ->orderBy('type')
                 ->all();
 
    echo $this->render('joints', array(
      'params'  => $params,
      'rows'    => $rows,
      'methods' => $methods,
    ));
  }


  /**
  Элементы трубопровода
   */
  public function actionUnits() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $unit_tn = Unit::tableName();

    $metaArray = new \MetaArray();

    $rows = Unit::find()
              ->where( $metaArray->serialize_sql( $unit_tn ) )
              ->all();

    echo $this->render('units', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }


  /**
  Журнал НК
   */
  public function actionLog() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn   = Doc::tableName();
    $joint_tn = Joint::tableName();
    $entry_tn = JointEntry::tableName();

    $metaArray = new \MetaArray();

    $sql = 'SELECT "%2$s".name as %2$s_name, "%1$s".name as %1$s_name, "%2$s".*, "%1$s".*, "%3$s".*
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id,
  "%2$s"
    ON "%2$s".id = _joints_id
WHERE
  %4$s AND %5$s AND %6$s
ORDER BY "%2$s".joint_pre1, "%2$s".joint_seq DESC, "%2$s".joint_sign1
';
    $where4 = $metaArray->serialize_sql( $doc_tn );
    $where5 = $metaArray->serialize_sql( $joint_tn );
    $where6 = $metaArray->serialize_sql( $entry_tn );
    $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $where4, $where5, $where6 );
    $command = $connection->createCommand( $sql );
    $rows = $command->queryAll();

    echo $this->render('log', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }

}

?>

controllers/ViewController.php
<?php // Stan 2013-05-24

namespace app\controllers;

use Yii;
use \yii\web\Controller;
use \yii\base\HttpException;

require_once 'lib/meta_array.php';
require_once 'lib/sql.php';
require_once 'lib/view.php';
require_once 'lib/common.php';


class ViewController extends Controller {
  public $layout = '@app/views/layouts/view';


  /**
  Просмотр значений колонок всех таблиц
   */
  public function actionIndex() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $metaArray = new \MetaArray();

    $tables = array();
  
    $schemas = $connection->schema->tableSchemas;
    foreach( $schemas as $schema ):
      $tablename = $schema->name;
      $tableparams = $metaArray->get($tablename);
  
      // Получаем кол-во записей в таблице
      list($count, $all) = sql_count2($connection, $tablename, '*', $metaArray);

      // Получаем список primaryKey и foreignKeys
      $pfkeys = array();
      if ( $schema->primaryKey )
        $pfkeys[] = $schema->primaryKey[0];
      if ( $schema->foreignKeys )
        foreach ( $schema->foreignKeys as $foreignKey ) {
          $pfkeys[] = array_keys($foreignKey)[1];
        } // foreach
  
      $columns = array();
      foreach ( $schema->columns as $columnname => $column ):
        if ( in_array($column->name, $pfkeys) )
          continue;
  
        if ( $column->dbType == "BLOB" )
          continue;
  
        $columncount = sql_count($connection, $tablename, "DISTINCT(`" . $columnname . "`)", $metaArray);
        $values = get_distinct($connection, $tablename, $column->name, $metaArray);
  
        $columns[$columnname] = array($columncount, $column->type, $values);
      endforeach;
  
      $tables[$tablename] = array($count, $all, $columns);
    endforeach;

    echo $this->render('index', array(
      'params'    => $params,
      'metaArray' => $metaArray,
      'tables'    => $tables,
    ));
  }


  /**
  Страница отладки
   */
  public function actionDebug() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $metaArray = new \MetaArray();

    echo $this->render('debug', array(
      'params'    => $params,
      'metaArray' => $metaArray,
    ));
  }


  /**
  Просмотр значений заданной колонки
   */
  public function actionColumn() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('table', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Table parameter required!',
      ));
      return;
    }

    if ( !array_key_exists('column', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Column parameter required!',
      ));
      return;
    }

    $table = $params['table'];

    $tables = $connection->schema->tableNames;
    if ( !in_array($table, $tables) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Table is missing!',
      ));
      return;
    }

    $column = $params['column'];

//     $schemas = $connection->schema->tableSchemas;
//     if ( !in_array($column, $schemas[*]['columns']) ) {
//       echo $this->render('/site/error', array(
//         'name'    => 'Error',
//         'message' => 'Column is missing!',
//       ));
//       return;
//     }

    $all = sql_count($connection, $table, "DISTINCT(`" . $column . "`)", NULL);
    $rows = get_distinct($connection, $table, $column, NULL, NULL);

    echo $this->render('column', array(
      'params' => $params,
      'table'  => $table,
      'column' => $column,
      'all'    => $all,
      'rows'   => $rows,
    ));
  }


  /**
  Просмотр заданной таблицы
   */
  public function actionTable() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('table', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Table parameter required!',
      ));
      return;
    }

    $table = $params['table'];

    $tables = $connection->schema->tableNames;
    if ( !in_array($table, $tables) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Table is missing!',
      ));
      return;
    }

    $metaArray = new \MetaArray();

    list($count, $all) = sql_count2($connection, $table, '*', $metaArray);

    $schema = get_schema($connection, $table);
    $columns = $schema->columns;

    $sortby = array_key_exists('name', $columns) ? 'name' : NULL;
    $rows = sql_select($connection, $table, '*', $metaArray, $sortby);

    echo $this->render('table', array(
      'params' => $params,
      'count'  => $count,
      'all'    => $all,
      'rows'   => $rows,
    ));
  }


  /**
  Просмотр сведений о базе данных
   */
  public function actionDbInfo() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    // Скрываем имя пользователя / пароль
    $connection->username = '*******';
    $connection->password = '*******';

    echo $this->render('dbinfo', array(
      'params'     => $params,
      'connection' => $connection,
    ));
  }


  /**
  Просмотр сведений о таблицах
   */
  public function actionTablesInfo() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $schemas = $connection->schema->tableSchemas;

    echo $this->render('tablesinfo', array(
      'params'  => $params,
      'schemas' => $schemas,
    ));
  }


}

?>

views/view/column.php
<?php // Stan 2013-09-24

use yii\helpers\Html;

$this->title = 'Column';
$this->params['breadcrumbs'][] = 'View';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  unset($params['table']);
  unset($params['column']);

  echo Html::a('Return', array_merge(array('view/index'), $params), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  echo "Records: " . $all . "<br /><br />\n";

  $params_d = $params;
  unset($params_d[$table][$column]);

  start_table();

  foreach ( $rows as $row ):

    if ( $row === NULL ) {
      $value = '<i>NULL</i>';
      $params_d[$table][$column] = array('is' => 'NULL');
    } elseif ( $row === '' ) {
      $value = '<i>empty</i>';
      $params_d[$table][$column] = $row;
    } else {
      $value = $row;
      $params_d[$table][$column] = $row;
    } // if

    echo "  <tr>\n";
    echo '<td>' . Html::a( $value, array_merge(array('view/index'), $params_d) ) . '</td>';
    echo '<td>' . gettype( $row ) . '</td>';
    $hexes = str_split( bin2hex( $row ), 2 );
    $text = "";   // $text = join( ' ', $hexes );
    foreach ( $hexes as $hex ) {
      $ord = hexdec( $hex );
      $title = htmlspecialchars( chr( $ord ) );
      $text .= '<span title="' . $title . '">' . $hex. '</span> ';
    } // foreach
    echo '<td>' . $text . "</td>\n";
    echo "  </tr>\n";

  endforeach;

  stop_table();

?>

views/view/dbinfo.php
<?php // Stan 2013-05-26

use yii\helpers\Html;

$this->title = 'DB Info';
$this->params['breadcrumbs'][] = 'View';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index', array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('Tables Info', array('view/tables-info'), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  // Выводим $connection
  print_ra($connection);

?>

views/view/debug.php
<?php // Stan 2013-09-19

use yii\helpers\Html;

$this->title = 'Debug';
$this->params['breadcrumbs'][] = $this->title;


echo '<pre>' . $_file_ . "</pre>\n";
echo '<pre>';
print_r( $_params_ );
echo '</pre>';
echo "<br />\n";

echo "<hr />\n";

$localVariables = compact(array_keys(get_defined_vars()));
echo '<pre>';
var_dump( $localVariables );
echo '</pre>';

?>

views/view/index.php
<?php // Stan 2013-05-24

use yii\helpers\Html;

$this->title = 'View';
// $this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index',  array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('Docs',   array_merge(array('ndt/docs'),   $params), array('class' => 'btn'));
  echo Html::a('Joints', array_merge(array('ndt/joints'), $params), array('class' => 'btn'));
  echo Html::a('Units',  array_merge(array('ndt/units'),  $params), array('class' => 'btn'));

  echo Html::a('Reset', array($params['r']), array('class' => 'btn'));

?>
</div>

<div class="pull-right btn-group">
<?php

  echo Html::a('Debug', array_merge(array('view/debug'), $params), array('class' => 'btn'));

?>
</div>

<br /><hr />


<?php if(Yii::$app->session->hasFlash('error')): ?>
<div class="alert alert-error">
  <?php echo Yii::$app->session->getFlash('error'); ?>
</div>
<?php endif; ?>

<?php if(Yii::$app->session->hasFlash('success')): ?>
<div class="alert alert-success">
  <?php echo Yii::$app->session->getFlash('success'); ?>
</div>
<?php endif; ?>


<?php

  foreach ( $tables as $tablename => $tableinfo ):
    $tableparams = $metaArray->get($tablename);

    list($count, $all, $columns) = $tableinfo;

    $a = Html::a($tablename, array_merge(array('view/table'), $params, array('table' => $tablename)));
    echo <<<EOD
<fieldset><legend>$a ($count)</legend>
<table border="1">\n
EOD;

    foreach ( $columns as $columnname => $columninfo ):
      list($columncount, $columntype, $values) = $columninfo;

      if ( isset( $tableparams[$columnname] ) ) {
        $params_d = $params;
        unset($params_d[$tablename][$columnname]);
        $reset_a = Html::a('<i>Сбросить</i>', array_merge(array(''), $params_d));
      } else
        $reset_a = '';

      if ( $reset_a )
        echo '<tr><td><b><i>' . $columnname . '</i></b><td>' . $columncount . "<td>\n";
      else
        echo '<tr><td>' . $columnname . '<td>' . $columncount . "<td>\n";

      $valuesshow = 0;
      $columnlen = 0;
      foreach ( $values as $value ):
        $params_d = $params;

        if ( $value === NULL ) {
          $params_d[$tablename][$columnname] = array('is' => 'NULL');
          $value = '<i>NULL</i>';
        } elseif ( $value === '' ) {
          $params_d[$tablename][$columnname] = $value;
          $value = '<i>empty</i>';
        } else
          $params_d[$tablename][$columnname] = $value;
        echo Html::a('[' . $value . ']', array_merge(array(''), $params_d));
        if ( strlen($value) > 80 )
          echo "<br />\n";
        else
          echo ' ';

        $valuesshow += 1;

        $columnlen += strlen($value);
        if ( $columnlen > 1000 )
          break;
      endforeach;

      if ( $valuesshow < $columncount )
        echo '...(' . $valuesshow . ') ' .
             Html::a('<i>Показать все</i>', array_merge(array('view/column'),
                     $params, array('table' => $tablename, 'column' => $columnname))) .
             "\n";

      echo $reset_a . "</td></tr>\n";

    endforeach;

    echo "</table></fieldset><br />\n";

  endforeach;

?>

views/view/table.php
<?php // Stan 2013-05-26

use yii\helpers\Html;

$this->title = 'Table';
$this->params['breadcrumbs'][] = 'View';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index', array_merge(array('view/index'), $params), array('class' => 'btn'));

//echo Html::a('Reset', array($params['r']), array('class' => 'btn'));
  $r = array($params['r']);
  $params = array('table' => $params['table']);
  echo Html::a('Reset', array_merge($r, $params), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  echo 'Records: ' . $all . "<br />\n";
  echo 'Shown: ' . $count . "<br /><br />\n";

  table_rows( $rows, $params['table'], $params );

?>

views/view/tablesinfo.php
<?php // Stan 2013-05-26

use yii\helpers\Html;

$this->title = 'Tables Info';
$this->params['breadcrumbs'][] = 'View';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index', array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('DB Info', array('view/db-info'), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  echo Html::a('Сведения о базе данных', array('view/db-info'), array('class' => 'btn'));
  echo "<br /><br />\n";

  // Выводим $schemas в виде таблицы без поля 'columns'
  start_table();

  $headers = array();
  $columns = array();
  foreach ( $schemas as $schema ):
    $columns[$schema->name] = $schema->columns;

    if ( !$headers ) {
      echo "  <tr>\n";
      foreach ( $schema as $key => $value ):
        if ( $key == 'columns' )
          continue;

        echo '    <th>' . $key . "</th>\n";
        $headers[] = $key;
      endforeach;
      echo "  </tr>\n";
    } // if

    echo "  <tr>\n";
    foreach ( $headers as $key ) {
      echo '    <td>' . sprint_ra( $schema->$key ) . "</td>\n";
    } // foreach
    echo "  </tr>\n";

  endforeach;

  stop_table();


  echo "<br />\n";


  // Выводим поле 'columns' в виде таблицы
  start_table();

  $headers = array();
  foreach ( $columns as $tablename => $column ):
    $count = count($column);
    foreach ( $column as $columnname => $columninfo ):
  
      if ( !$headers ) {
        echo "  <tr>\n";
        echo "    <th>#</th>\n";
//         echo "    <th>#</th>\n";
        foreach ( $columninfo as $key => $value ) {
          echo '    <th>' . $key . "</th>\n";
          $headers[] = $key;
        } // foreach
        echo "  </tr>\n";
      } // if
  
      echo "  <tr>\n";
      if ( $count ) {
        echo '    <td rowspan="' . $count . '">' . $tablename . "</td>\n";
        $count = 0;
      } // if
//       echo '    <td>' . $columnname . "</td>\n";
      foreach ( $headers as $key ) {
        echo '    <td>' . sprint_ra( $columninfo->$key ) . "</td>\n";
      } // foreach
      echo "  </tr>\n";
  
    endforeach;
  endforeach;

  stop_table();

?>