controllers/NdtController.php
<?php // Stan 2013-09-20

namespace app\controllers;

use Yii;
use \yii\web\Controller;
use \yii\base\HttpException;

use app\models\Doc;
use app\models\Unit;
use app\models\Entry;
use app\models\Joint;
use app\models\JointEntry;

require_once 'lib/meta_array.php';
require_once 'lib/sql.php';
require_once 'lib/view.php';
require_once 'lib/common.php';


class NdtController extends Controller {
  public $layout = '@app/views/layouts/view';


  /**
  Index
   */
  public function actionIndex() {
    list($route, $params) = Yii::$app->request->resolve();

    echo $this->render('debug', array(
      'params' => $params,
    ));
  }


  /**
  Документы
   */
  public function actionDocs() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn = Doc::tableName();

    $metaArray = new \MetaArray();

    $rows = Doc::find()
              ->where( $metaArray->serialize_sql( $doc_tn ) )
              ->all();

    echo $this->render('docs', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }


  /**
  Cтыки
   */
  public function actionJoints() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn   = Doc::tableName();
    $joint_tn = Joint::tableName();
    $entry_tn = JointEntry::tableName();

    $metaArray = new \MetaArray();

    $sql = 'SELECT DISTINCT "%2$s".id, "%2$s".name
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id,
  "%2$s"
    ON "%2$s".id = _joints_id
WHERE
  %4$s AND %5$s AND %6$s
ORDER BY "%2$s".name
';
    $where4 = $metaArray->serialize_sql( $doc_tn );
    $where5 = $metaArray->serialize_sql( $joint_tn );
    $where6 = $metaArray->serialize_sql( $entry_tn );
    $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $where4, $where5, $where6 );
    $command = $connection->createCommand( $sql );
    $joints = $command->queryAll();

    $rows = array();
    foreach ( $joints as $joint ) {
      $id = $joint['id'];
      $name = $joint['name'];

      $sql = 'SELECT "%1$s".*, "%3$s".decision, "%3$s".remarks
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id
WHERE
  _joints_id = \'%4$s\'
';
      $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $id );
      $command = $connection->createCommand( $sql );
      $docs = $command->queryAll();
 
      $rows2 = array();
      foreach ( $docs as $doc ) {
        $rows2[$doc['type']][] = array($doc['name'], $doc['kind'], $doc['decision'], $doc['remarks']);
      } // foreach

      $rows[] = array($id, $name, $rows2);
    } // foreach
 
    $methods = Doc::find()
                 ->select('type')
                 ->distinct('type')
                 ->orderBy('type')
                 ->all();
 
    echo $this->render('joints', array(
      'params'  => $params,
      'rows'    => $rows,
      'methods' => $methods,
    ));
  }


  /**
  Элементы трубопровода
   */
  public function actionUnits() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $unit_tn = Unit::tableName();

    $metaArray = new \MetaArray();

    $rows = Unit::find()
              ->where( $metaArray->serialize_sql( $unit_tn ) )
              ->all();

    echo $this->render('units', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }


  /**
  Журнал НК
   */
  public function actionLog() {
    $connection = Yii::$app->db;
    list($route, $params) = Yii::$app->request->resolve();

    $doc_tn   = Doc::tableName();
    $joint_tn = Joint::tableName();
    $entry_tn = JointEntry::tableName();

    $metaArray = new \MetaArray();

    $sql = 'SELECT "%2$s".name as %2$s_name, "%1$s".name as %1$s_name, "%2$s".*, "%1$s".*, "%3$s".*
FROM
  "%3$s"
  INNER JOIN 
  "%1$s"
    ON "%1$s".id = _docs_id,
  "%2$s"
    ON "%2$s".id = _joints_id
WHERE
  %4$s AND %5$s AND %6$s
ORDER BY "%2$s".joint_pre1, "%2$s".joint_seq DESC, "%2$s".joint_sign1
';
    $where4 = $metaArray->serialize_sql( $doc_tn );
    $where5 = $metaArray->serialize_sql( $joint_tn );
    $where6 = $metaArray->serialize_sql( $entry_tn );
    $sql = sprintf( $sql, $doc_tn, $joint_tn, $entry_tn, $where4, $where5, $where6 );
    $command = $connection->createCommand( $sql );
    $rows = $command->queryAll();

    echo $this->render('log', array(
      'params' => $params,
      'rows'   => $rows,
    ));
  }

}

?>

controllers/OneController.php
<?php // Stan 2013-09-17

namespace app\controllers;

use Yii;
use \yii\web\Controller;
use \yii\base\HttpException;

use app\models\Dir;
use app\models\File;
use app\models\Handler;
use app\models\FileProcessing;
use app\models\Sheet;
use app\models\Doc;
use app\models\Unit;
use app\models\Entry;
use app\models\Joint;
use app\models\JointEntry;

require_once 'lib/meta_array.php';
require_once 'lib/sql.php';
require_once 'lib/view.php';
require_once 'lib/common.php';


class OneController extends Controller {
  public $layout = '@app/views/layouts/view';


  /**
  Index
   */
  public function actionIndex() {
    list($route, $params) = Yii::$app->request->resolve();

    echo $this->render('debug', array(
      'params' => $params,
    ));
  }


  /**
  Dirs
   */
  public function actionDirs() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $dirs_tn = Dir::tableName();

    $id = $params['id'];
    $dir = Dir::find()
             ->where(array('id' => $id))
             ->one();

    $files = $dir
               ->getFiles()
               ->all();

    echo $this->render($dirs_tn, array(
      'params' => $params,
      'dir'    => $dir,
      'files'  => $files,
    ));
  }


  /**
  Files
   */
  public function actionFiles() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $files_tn = File::tableName();

    $id = $params['id'];
    $file = File::find()
              ->where(array('id' => $id))
              ->one();
 
    $dir = $file
             ->getDir()
             ->one();

    $fileprocessings = $file
                         ->getFileProcessings()
                         ->all();

//  $sheets = $file
//              ->getSheets()
//              ->all();

    echo $this->render($files_tn, array(
      'params'          => $params,
      'dir'             => $dir,
      'file'            => $file,
      'fileprocessings' => $fileprocessings,
//    'sheets'          => $sheets,
    ));
  }


  /**
  Handlers
   */
  public function actionHandlers() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $handlers_tn = Handler::tableName();

    $id = $params['id'];
    $handler = Handler::find()
                 ->where(array('id' => $id))
                 ->one();

    $fileprocessings = $handler
                         ->getFileProcessings()
                         ->all();

    echo $this->render($handlers_tn, array(
      'params'          => $params,
      'handler'         => $handler,
      'fileprocessings' => $fileprocessings,
    ));
  }


  /**
  File Processings
   */
  public function actionFileprocessings() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $fileprocessings_tn = FileProcessing::tableName();

    $id = $params['id'];
    $fileprocessing = FileProcessing::find()
                        ->where(array('id' => $id))
                        ->one();
 
    $file = $fileprocessing
            ->getFile()
            ->one();

    $dir = $file
             ->getDir()
             ->one();

    $handler = $fileprocessing
                 ->getHandler()
                 ->one();

    $sheets = $fileprocessing
                ->getSheets()
                ->all();

    echo $this->render($fileprocessings_tn, array(
      'params'         => $params,
      'dir'            => $dir,
      'file'           => $file,
      'handler'        => $handler,
      'fileprocessing' => $fileprocessing,
      'sheets'         => $sheets,
    ));
  }


  /**
  Sheets
   */
  public function actionSheets() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $sheets_tn = Sheet::tableName();

    $id = $params['id'];
    $sheet = Sheet::find()
               ->where(array('id' => $id))
               ->one();
 
    $fileprocessing = $sheet
                        ->getFileProcessing()
                        ->one();

    $file = $fileprocessing
              ->getFile()
              ->one();

    $dir = $file
             ->getDir()
             ->one();

    $handler = $fileprocessing
                 ->getHandler()
                 ->one();

    $docs = $sheet
              ->getDocs()
              ->all();

    echo $this->render($sheets_tn, array(
      'params'         => $params,
      'dir'            => $dir,
      'file'           => $file,
      'handler'        => $handler,
      'fileprocessing' => $fileprocessing,
      'sheet'          => $sheet,
      'docs'           => $docs,
    ));
  }


  /**
  Docs
   */
  public function actionDocs() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $docs_tn = Doc::tableName();

    $id = $params['id'];
    $doc = Doc::find()
             ->where(array('id' => $id))
             ->one();
 
    $sheet = $doc
               ->getSheet()
               ->one();

    $fileprocessing = $sheet
                        ->getFileProcessing()
                        ->one();

    $file = $fileprocessing
              ->getFile()
              ->one();

    $dir = $file
             ->getDir()
             ->one();

    $handler = $fileprocessing
                 ->getHandler()
                 ->one();

    $entries = $doc
                 ->getEntries()
                 ->all();

    $joint_entries = $doc
                       ->getJointEntries()
                       ->all();

    echo $this->render($docs_tn, array(
      'params'         => $params,
      'dir'            => $dir,
      'file'           => $file,
      'handler'        => $handler,
      'fileprocessing' => $fileprocessing,
      'sheet'          => $sheet,
      'doc'            => $doc,
      'entries'        => $entries,
      'joint_entries'  => $joint_entries,
    ));
  }


  /**
  Units
   */
  public function actionUnits() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $units_tn = Unit::tableName();

    $id = $params['id'];
    $unit = Unit::find()
              ->where(array('id' => $id))
              ->one();

    $entries = $unit
                 ->getEntries()
                 ->all();

    echo $this->render($units_tn, array(
      'params'  => $params,
      'unit'    => $unit,
      'entries' => $entries,
    ));
  }


  /**
  Entries
   */
  public function actionEntries() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $entries_tn = Entry::tableName();

    $id = $params['id'];
    $entry = Entry::find()
               ->where(array('id' => $id))
               ->one();
 
    $unit = $entry
             ->getUnit()
             ->one();

    $doc = $entry
             ->getDoc()
             ->one();

    $sheet = $doc
               ->getSheet()
               ->one();

    $fileprocessing = $sheet
                        ->getFileProcessing()
                        ->one();

    $file = $fileprocessing
              ->getFile()
              ->one();

    $dir = $file
             ->getDir()
             ->one();

    $handler = $fileprocessing
                 ->getHandler()
                 ->one();

    echo $this->render($entries_tn, array(
      'params'         => $params,
      'dir'            => $dir,
      'file'           => $file,
      'handler'        => $handler,
      'fileprocessing' => $fileprocessing,
      'sheet'          => $sheet,
      'doc'            => $doc,
      'unit'           => $unit,
      'entry'          => $entry,
    ));
  }


  /**
  Joints
   */
  public function actionJoints() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',
        'message' => 'Parameter ID required!',
      ));
      return;
    }

    $joints_tn = Joint::tableName();

    $id = $params['id'];
    $joint = Joint::find()
               ->where(array('id' => $id))
               ->one();

    $joint_entries = $joint
                       ->getJointEntries()
                       ->all();

    echo $this->render($joints_tn, array(
      'params'        => $params,
      'joint'         => $joint,
      'joint_entries' => $joint_entries,
    ));
  }


  /**
  Joint Entries
   */
  public function actionJoint_entries() {
    list($route, $params) = Yii::$app->request->resolve();

    if ( !array_key_exists('id', $params) ) {
      echo $this->render('/site/error', array(
        'name'    => 'Error',

views/ndt/debug.php
<?php // Stan 2013-09-19

use yii\helpers\Html;

$this->title = 'Debug';
$this->params['breadcrumbs'][] = $this->title;


echo '<pre>' . $_file_ . "</pre>\n";
echo '<pre>';
print_r( $_params_ );
echo '</pre>';
echo "<br />\n";

echo "<hr />\n";

$localVariables = compact(array_keys(get_defined_vars()));
echo '<pre>';
var_dump( $localVariables );
echo '</pre>';

?>

views/ndt/docs.php
<?php // Stan 2013-08-27

use yii\helpers\Html;

$this->title = 'Docs';
$this->params['breadcrumbs'][] = 'NDT';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index',  array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('Docs',   array_merge(array('ndt/docs'),   $params), array('class' => 'btn'));
  echo Html::a('Joints', array_merge(array('ndt/joints'), $params), array('class' => 'btn'));
  echo Html::a('Units',  array_merge(array('ndt/units'),  $params), array('class' => 'btn'));

  echo Html::a('Reset', array($params['r']), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  table_rows( $rows, 'docs', $params );

?>

views/ndt/joints.php
<?php // Stan 2013-08-27

use yii\helpers\Html;

$this->title = 'Joints';
$this->params['breadcrumbs'][] = 'NDT';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index',  array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('Docs',   array_merge(array('ndt/docs'),   $params), array('class' => 'btn'));
  echo Html::a('Joints', array_merge(array('ndt/joints'), $params), array('class' => 'btn'));
  echo Html::a('Units',  array_merge(array('ndt/units'),  $params), array('class' => 'btn'));

  echo Html::a('Reset', array($params['r']), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  if ( isset( $rows ) ) {
    start_table();
  
    $columns = array('id', 'name');

    ////////
    // TH //
    ////////
    echo "  <tr>\n";
    echo "    <th>#</th>\n";

    foreach ( $columns as $column ) {
      echo '    <th>' . $column . "</th>\n";
    } // foreach

    foreach ( $methods as $method ) {
      echo '    <th>' . $method['type'] . "</th>\n";
    } // foreach

    echo "  </tr>\n";

    ////////
    // TD //
    ////////
    $seq = 1;
    foreach ( $rows as $row ):
      $docs = array_pop( $row );

      echo "  <tr>\n";
      echo '    <td class=null>' . $seq . "</td>\n";
      $seq++;

      $beginning = True;
      foreach ( $row as $column ) {
        if ( $beginning ) {
          $params = array('id' => $column);
          $column = Html::a('<i>' . $column . '</i>', array_merge(array('one/joints'), $params));
          $beginning = False;
        } // if
        echo '    <td>' . $column . "</td>\n";
      } // foreach

      foreach ( $methods as $method ):
        $type = $method['type'];
        if ( array_key_exists( $type, $docs ) ) {
          echo "    <td>\n";
          start_table();

          foreach ( $docs[$type] as $doc ) {
            $name = $doc[1] . ' ' . $doc[0] . '<br /><i><b>' . $doc[2] . '</b></i>';
            if ( $doc[3] )
              $name .= '<br /><i>' . $doc[3] . '</i>';
            echo '    <tr><td>' . $name . "</td></tr>\n";
//          echo '    <tr><td>' . sprint_ra($doc) . "</td></tr>\n";
          } // foreach

          stop_table();
          echo "    </td>\n";
        } else
          echo "    <td>-</td>\n";
      endforeach;

      echo "  </tr>\n";
  
    endforeach;
  
    stop_table();
  } // if

?>

views/ndt/log.php
<?php // Stan 2013-10-13

use yii\helpers\Html;

$this->title = 'Log';
$this->params['breadcrumbs'][] = 'NDT';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Return', array_merge(array('view/index'), $params), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  if ( $rows ) {
    start_table( '№ п/п',
'№ стыка по журналу или сварочной схеме, № журнала или схемы',
'Шифр сварщика или бригады, фамилия, инициалы',
'',
'Дата и способ контроля (Р, Г, М, У)',
'№ и дата выдачи',
'Заключение о годности (годен, исправить, вырезать, повторный контроль)',
'радиографа',
'начальника или инженера службы контроля качества',
'Замечания контролирующих лиц по качеству выполняемого контроля физическими методами сварных соединений с указанием фамилии, должности и даты записи',
'Дата и подпись ответственного лица об устранении нарушений' );

    $table = 'joints';
  
    $seq = 1;
    foreach ( $rows as $row ):
  
//    echo_row( $row, $seq, $table, $params );

      $joints_name = $row['joints_name'];

      $welders   = array();
      $welders_r = array();

      $welder_text = '';
      $welder_r_text = '';

      if ( $row['welders_root'] )
        foreach ( explode('/', $row['welders_root'] ) as $welder_id )
          $welders[] = $welder_id;
      else {
        $welders[] = '';
        $welders[] = '';
      }

      if ( $row['welders_fill1'] )
        foreach ( explode('/', $row['welders_fill1'] ) as $welder_id )
          $welders[] = $welder_id;
      else {
        $welders[] = '';
        $welders[] = '';
      }

      if ( $row['welders_fill2'] )
        foreach ( explode('/', $row['welders_fill2'] ) as $welder_id )
          $welders[] = $welder_id;
      else {
        $welders[] = '';
        $welders[] = '';
      }

      if ( $row['welders_cap'] )
        foreach ( explode('/', $row['welders_cap'] ) as $welder_id )
          $welders[] = $welder_id;
      else {
        $welders[] = '';
        $welders[] = '';
      }

      if ( $row['welder_r'] )
        foreach ( explode('/', $row['welder_r']) as $welder_id )
          $welders_r[] = $welder_id;

      foreach ( $welders as $welder_id ) {
        if ( $welder_id ) {
          $werder = get_weldername( $welder_id );
          $welder_text .= $welder_id . ' - ' . $werder . '<br />';
        } else
          $welder_text .= '<br />';
      } // foreach

      foreach ( $welders_r as $welder_id ) {
        $werder = get_weldername( $welder_id );
        $welder_r_text .= $welder_id . ' - ' . $werder . '<br />';
      } // foreach

      $date_type = $row['date_str'] . '<br>' . $row['type'];
      $docname_date = $row['docs_name'] . '<br>' . $row['date_str'];

//    $date_type = '<table><tr><td>' . $row['date_str'] . '<tr><td>' . $row['type'] . '</table>';
//    $docname_date = '<table><tr><td>' . $row['docs_name'] . '<tr><td>' . $row['date_str'] . '</table>';

      $row = array( $joints_name,
                    $welder_text,
                    $welder_r_text,
                    $date_type,
                    $docname_date,
                    $row['decision'],
                    '', '', '', '' );

      echo_row( $row, $seq, $table, $params );
      $seq++;

    endforeach;
  
    stop_table();
  } else
    echo '<i>Нет данных!</i><br />';


function get_weldername( $welder_id ) {
  switch ( $welder_id ) {
    case '': $werder = ''; break;
    case '004': $werder = 'Антонов Э.В.'; break;
    case '005': $werder = 'Панченко А.В.'; break;
    case '006': $werder = 'Канаев А.Б.'; break;
    case '007': $werder = 'Менделев Б.А.'; break;
    case '008': $werder = 'Васько А.Н.'; break;
    case '009': $werder = 'Волков Ю.П.'; break;
    case '010': $werder = 'Гимадеев Л.Р.'; break;
    case '011': $werder = 'Жиглов А.Ю.'; break;
    case '012': $werder = 'Серов В.Е.'; break;
    case '013': $werder = 'Болотский А.В.'; break;
    case '014': $werder = 'Басыров А.Р.'; break;
    case '015': $werder = 'Симоненко Ю.В.'; break;
    case '016': $werder = 'Демченко Н.М.'; break;
    case '017': $werder = 'Скачков Д.В.'; break;
    case '018': $werder = 'Макаренко А.С.'; break;
    case '019': $werder = 'Кукаркин В.И.'; break;
    case '020': $werder = 'Гуща Д.В.'; break;
    case '021': $werder = 'Вуколов В.Н.'; break;
    case '022': $werder = 'Хабутдинов М.Н.'; break;
    case '023': $werder = 'Кущенко А.М.'; break;
    case '024': $werder = 'Марков А.А.'; break;
    case '025': $werder = 'Марков М.А.'; break;
    case '026': $werder = 'Стенников С.А.'; break;
    case '027': $werder = 'Жуков А.А.'; break;
    case '028': $werder = 'Кудряшов Н.И.'; break;
    case '029': $werder = 'Ярулин Т.Р.'; break;
    case '030': $werder = 'Алексеев А.В.'; break;
    case '031': $werder = 'Шукшин А.А.'; break;
    case '032': $werder = 'Кабанец А.В.'; break;
    case '033': $werder = 'Стародубов С.В.'; break;
    case '034': $werder = 'Копченко В.А.'; break;
    case '035': $werder = 'Арманаш А.П.'; break;
    case '036': $werder = 'Крылов С.Н.'; break;

    default: $werder = '-';
  } // switch
  
  return $werder;
} // function

?>

views/ndt/units.php
<?php // Stan 2013-10-13

use yii\helpers\Html;

$this->title = 'Units';
$this->params['breadcrumbs'][] = 'NDT';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="pull-left btn-group">
<?php

  echo Html::a('Index',  array_merge(array('view/index'), $params), array('class' => 'btn'));
  echo Html::a('Docs',   array_merge(array('ndt/docs'),   $params), array('class' => 'btn'));
  echo Html::a('Joints', array_merge(array('ndt/joints'), $params), array('class' => 'btn'));
  echo Html::a('Units',  array_merge(array('ndt/units'),  $params), array('class' => 'btn'));

  echo Html::a('Reset', array($params['r']), array('class' => 'btn'));

?>
</div>
<br /><hr />


<?php

  table_rows( $rows, 'units', $params );

?>